apiVersion: v2
appVersion: 1.0.0
description: ACME settings chart for my home cluster
name: lets-encrypt-acme
version: 1.0.0
home: https://github.com/jetersen/home.cluster
maintainers:
- name: jetersen
  url: https://github.com/jetersen
