---
- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker and its dependecies
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ansible user to docker group
  user:
    name: '{{ ansible_user }}'
    group: docker
