kind: Service
apiVersion: v1
metadata:
  name: wireguard-external
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalName }}
