repositories:
- name: jetstack
  url: https://charts.jetstack.io
releases:
- name: cert-manager
  chart: jetstack/cert-manager
  namespace: cert-manager
  createNamespace: true
  wait: true
  version: v0.15.1
  values:
  - ../config/cert-manager.yaml

- name: acme
  chart: ../charts/acme
  namespace: cert-manager
  wait: true
  values:
  - ../config/acme.yaml
  secrets:
  - ../secrets/config/acme.yaml
