repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- name: external-dns
  chart: bitnami/external-dns
  namespace: external-dns
  createNamespace: true
  wait: true
  version: 3.2.1
  values:
  - ../config/external-dns.yaml
  secrets:
  - ../secrets/config/external-dns.yaml

- name: dyndns
  chart: ../charts/dyndns
  namespace: external-dns
  wait: true
  values:
  - hostname: public.ingress.jetersen.dev
