repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
releases:
- name: nginx-ingress
  chart: ingress-nginx/ingress-nginx
  namespace: nginx-ingress
  createNamespace: true
  version: 2.7.0
  wait: true
  timeout: 300
  atomic: true
  values:
  - ../config/nginx-ingress.yaml
