environments:
  default:
    secrets:
    - ../secrets/config/dex.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
releases:
- name: prometheus-operator
  chart: stable/prometheus-operator
  namespace: monitoring
  createNamespace: true
  version: 8.15.6
  wait: true
  timeout: 300
  atomic: true
  values:
  - ../config/prometheus-operator.yaml.gotmpl
